using System;
using System.Diagnostics;
using System.IO;
using BOA.CodeGeneration.Util;
using BOA.Common.Helpers;

namespace BOA.OneDesigner.Starter
{
    class Program
    {
        #region Constants
        const string destinationCopyDirectory = @"D:\BOA\BOA.OneDesigner\";
        #endregion

        #region Static Fields
        static readonly string destinationDirectory = Path.GetTempPath();
        #endregion

        #region Public Methods
        public static void Main()
        {
            EmbeddedAssembly.AddAssembly("WhiteStone.dll", typeof(Program).Assembly.ManifestModule.Name, "BOA.OneDesigner.Starter.WhiteStone.dll");
            EmbeddedAssembly.AddAssembly("Newtonsoft.Json.dll", typeof(Program).Assembly.ManifestModule.Name, "BOA.OneDesigner.Starter.Newtonsoft.Json.dll");
            EmbeddedAssembly.AddAssembly("ICSharpCode.SharpZipLib.dll", typeof(Program).Assembly.ManifestModule.Name, "BOA.OneDesigner.Starter.ICSharpCode.SharpZipLib.dll");
            EmbeddedAssembly.AttachToCurrentDomain();

            AttachToZippedReferences();

            
            try
            {
                
                DownloadAndExtractZipFromTfs();
            }
            catch (Exception e)
            {
                Log.Push(e);
            }

            StartProcess();
        }
        #endregion

        #region Methods
        static void AttachToZippedReferences()
        {
            Trace("Started to extract zip files.");

            const string internalFilePath = "Zips";

            //EmbeddedResourceHelper.Extract(typeof(Program).Namespace, destinationDirectory, internalFilePath, "WhiteStone.zip");
            EmbeddedResourceHelper.Extract(typeof(Program).Namespace, destinationDirectory, internalFilePath, "BOA.TfsAccess.zip");

            Trace("Finished extract zip files.");

            
            AppDomain.CurrentDomain.AddAssemblySearchDirectory(ZipHelper.UnZip(destinationDirectory + "BOA.TfsAccess.zip"));
            //AppDomain.CurrentDomain.AddAssemblySearchDirectory(ZipHelper.UnZip(destinationDirectory + "WhiteStone.zip"));
        }

        static void DownloadAndExtractZipFromTfs()
        {
            Trace("Started to fetch data from tfs");

            const string targetPath = "D:\\work\\BOA.CardModules\\Dev\\AutoGeneratedCodes\\BOA.OneDesigner\\BOA.OneDesigner.zip";

            var tempDirectoryZipFile = destinationDirectory + Path.GetFileName(targetPath);

            TFSAccessForBOA.DownloadFile(targetPath, tempDirectoryZipFile);

            ZipHelper.UnZip(tempDirectoryZipFile, destinationCopyDirectory);
        }

        static void StartProcess()
        {
            const string processLocation = destinationCopyDirectory + "WhiteStone.UI.Container.exe";

            Process.Start(processLocation);
        }

        static void Trace(string message)
        {
            Console.WriteLine(message);
            Log.Push(message);
        }
        #endregion
    }
}