using System;
using System.Diagnostics;
using System.IO;
using BOA.CodeGeneration.Util;
using BOA.Common.Helpers;

namespace BOA.OneDesigner.Starter
{
    class Program
    {
        #region Methods
        static void Main()
        {
            var destinationDirectory = Path.GetTempPath();

            const string internalFilePath = "Zips";

            EmbeddedResourceHelper.Extract(typeof(Program).Namespace, destinationDirectory, internalFilePath, "WhiteStone.zip");
            EmbeddedResourceHelper.Extract(typeof(Program).Namespace, destinationDirectory, internalFilePath, "BOA.TfsAccess.zip");

            new ZipAssemblyResolver(destinationDirectory + "WhiteStone.zip").AttachToCurrentDomain();
            new ZipAssemblyResolver(destinationDirectory + "BOA.TfsAccess.zip").AttachToCurrentDomain();

            const string targetPath = "D:\\work\\BOA.CardModules\\Dev\\AutoGeneratedCodes\\BOA.OneDesigner\\BOA.OneDesigner.zip";

            var tempDirectoryZipFile = destinationDirectory + Path.GetFileName(targetPath);

            TFSAccessForBOA.DownloadFile(targetPath, tempDirectoryZipFile);

            var destinationCopyDirectory = @"D:\BOA\BOA.OneDesigner\";

            ZipHelper.UnZip(tempDirectoryZipFile, destinationCopyDirectory);

            FileHelper.CreateDirectoryIfNotExists(destinationCopyDirectory + "MainForm\\");

            var sourceFileName = destinationCopyDirectory + "View.json";
            var destFileName   = destinationCopyDirectory + "MainForm\\View.json";

            File.Delete(destFileName);
            File.Move(sourceFileName, destFileName);


            var processLocation = destinationCopyDirectory + "WhiteStone.UI.Container.exe";

            
            Process.Start(processLocation);



        }
        #endregion
    }
}