EntityContractBase: CardContractBase
UsingLines:
  - using System;
  - using CardContractBase = BOA.Common.Types.CardContractBase;
AssemblyReferences:
  - <Reference Include="BOA.Common"><HintPath>D:\BOA\Server\bin\BOA.Common.dll</HintPath></Reference>
  - <Reference Include="System" />
  - <Reference Include="System.Core" />