using System.Collections.Generic;
using System.IO;
using System.Linq;
using BOA.Common.Helpers;
using BOAPlugins.ExportingModel;

namespace BOAPlugins.FormApplicationGenerator
{
    class FileExporter
    {
        #region Constructors
        public FileExporter(Model model)
        {
            Model = model;
        }
        #endregion

        #region Properties
        Model Model { get; }
        #endregion

        #region Public Methods
        public void ExportFiles()
        {
            var typesFolder = Model.TypesProjectFolder;

            var oneProjectFolder = Model.OneProjectFolder;

            Util.WriteFileIfContentNotEqual(typesFolder + Model.FormName + "ListForm.cs", TypeFileForListForm.GenerateCode(Model));
            Util.WriteFileIfContentNotEqual(typesFolder + Model.FormName + "Form.cs", TypeFileForDefinitionForm.GenerateCode(Model));

            Util.WriteFileIfContentNotEqual(Model.OrchestrationProjectFolder + Model.FormName + "ListForm.cs", OrchestrationFileForListForm.GenerateCode(Model));
            Util.WriteFileIfContentNotEqual(Model.OrchestrationProjectFolder + Model.FormName + "Form.cs", OrchestrationFileForDefinitionForm.GenerateCode(Model));

            FormAssistantProjectInitializer.Initialize(Model);

            Util.WriteFileIfContentNotEqual(oneProjectFolder + @"ClientApp\pages\" + Model.FormName + "ListForm.tsx", ListFormTsxFile.GenerateCode(Model));
            Util.WriteFileIfContentNotEqual(oneProjectFolder + @"ClientApp\pages\" + Model.FormName + "Form.tsx", DefinitionFormTsxFile.GenerateCode(Model));

            var autoGeneratedConfigFilePath = oneProjectFolder + @"ClientApp\models\AutoGeneratedModelsConfig.json";

            UpdateAutoGeneratedModelsConfig(autoGeneratedConfigFilePath);
        }
        #endregion

        #region Methods
        static string CannotBeEmpty(string labelName)
        {
            return labelName + " can not be empty";
        }

        static void TryAddIfNotExists(ICollection<string> ExportClassNames, string fullTypeName)
        {
            if (ExportClassNames.Contains(fullTypeName))
            {
                return;
            }

            ExportClassNames.Add(fullTypeName);
        }

        void UpdateAutoGeneratedModelsConfig(string autoGeneratedConfigFilePath)
        {
            var config = JsonHelper.Deserialize<ExportContract>(File.ReadAllText(autoGeneratedConfigFilePath));

            var assemblyName = Model.NamespaceNameForType + ".dll";
            var exportInfo   = config.ExportInfoList.FirstOrDefault(x => x.Assembly == assemblyName);
            if (exportInfo == null)
            {
                exportInfo = new ExportInfo
                {
                    Assembly         = assemblyName,
                    ExportClassNames = new List<string>()
                };

                config.ExportInfoList.Add(exportInfo);
            }

            var ns = Model.NamespaceNameForType;

            var ExportClassNames = exportInfo.ExportClassNames;

            TryAddIfNotExists(ExportClassNames, ns + "." + Model.DefinitionFormDataClassName);
            TryAddIfNotExists(ExportClassNames, ns + "." + Model.FormName + "FormState");
            TryAddIfNotExists(ExportClassNames, ns + "." + Model.FormName + "FormDataSource");
            TryAddIfNotExists(ExportClassNames, ns + "." + Model.FormName + "FormRequest");

            TryAddIfNotExists(ExportClassNames, ns + "." + Model.FormName + "ListFormState");
            TryAddIfNotExists(ExportClassNames, ns + "." + Model.FormName + "ListFormDataSource");
            TryAddIfNotExists(ExportClassNames, ns + "." + Model.FormName + "ListFormRequest");
            TryAddIfNotExists(ExportClassNames, ns + "." + Model.FormName + "ListFormData");

            Util.WriteFileIfContentNotEqual(autoGeneratedConfigFilePath, JsonHelper.Serialize(config));
        }
        #endregion
    }
}