ConnectionString: Data Source = (LocalDB)\MSSQLLocalDB; AttachDbFilename = D:\github\WhiteStone\BOA.EntityGeneration.SchemaToEntityExporting.Test\SampleDatabase.mdf; Integrated Security = True
TableCatalog: D:\GITHUB\WHITESTONE\BOA.ENTITYGENERATION.SCHEMATOENTITYEXPORTING.TEST\SAMPLEDATABASE.MDF
DatabaseEnumName: SampleDatabase
CanExportBoaRepository: false
CanExportAllSchemaInOneClassRepository: true
SqlSequenceInformationOfTable:
RepositoryNamespace: BOA.Business.Kernel.Card.$(SchemaName)
SlnDirectoryPath: d:\temp\
EntityProjectDirectory: $(SlnDirectoryPath)Entity\$(SchemaName)\$(EntityNamespace)\
RepositoryProjectDirectory: $(SlnDirectoryPath)Entity\$(SchemaName)\$(RepositoryNamespace)\