OutputFilePath: $(EntityProjectDirectory)All.cs
EntityContractBase:
NamespaceName: BOA.Types.Kernel.Card.$(SchemaName)
ClassName: $(CamelCasedTableName)Contract
UsingLines:
  - using System;
AssemblyReferences:
  - <Reference Include="System" />
  - <Reference Include="System.Core" />