IntegrateWithTFSAndCheckInAutomatically: false
ProfileNames:
  - ACCOUNTING
  - ACQUIRING_2
  - ACQUIRING_KERNEL
  - BATCH_EMBOSS
  - CARD_APPLICATION
  - CARD_PAYMENT
  - CLEARING_COMMON
  - CRD_INSTANT
  - CreditCardExtract
  - EMC_MANAGEMENT
  - SWITCH_BKM
  - SYS_OPERATION
  - TMS2
  - VISA_MANAGEMENT_2
  - CC_OPERATIONS
  - CC_OPERATIONS_KERNEL
  - DLV_COURIER
SchemaNames:
  - BKM
  - BNS
  - CCA
  - CFG
  - CIS
  - CLR
  - COR
  - CRD
  - DBT
  - DLV
  - EMC
  - EMV
  - ESW
  - FRD
  - KMT
  - LOG
  - MRC
  - POS
  - PPD
  - PRM
  - RKL
  - STM
  - SWC
  - TMS
  - TRN
  - VIS
  - EMB
  - SYSOP
  - DIS
  - *