ConnectionString: Server=srvxdev\zumrut;Database=BOACard;Trusted_Connection=True;
DatabaseEnumName: BOACard
IntegrateWithTFSAndCheckInAutomatically: false
CustomSQLNamesDefinedToProfileSql: SELECT objectid AS Id FROM dbo.objects WITH (NOLOCK) WHERE profileid = @profileId AND objecttype = 'CUSTOMSQL'
CustomSQL_Get_SQL_Item_Info: SELECT text AS Sql, schemaname AS SchemaName, CAST(resultcollectionflag AS INT) AS SqlResultIsCollection FROM dbo.objects WITH (NOLOCK) WHERE profileid = @profileId AND objecttype = 'CUSTOMSQL' AND objectid = @id
SQL_GetProfileIdList: SELECT profileid as ProfileId FROM dbo.profileskt WITH (NOLOCK)
CustomSqlNamingPattern:
  ProfileName:
  CamelCasedCustomSqlName:
  SchemaName:
  CamelCasedResultName:
  InputClassName: $(CamelCasedCustomSqlName)Request
  ResultClassName: $(CamelCasedCustomSqlName)Contract
  RepositoryClassName: $(CamelCasedCustomSqlName)
  ReferencedEntityAccessPath: Types.Kernel.Card.$(SchemaName).$(CamelCasedResultName)Contract
  ReferencedEntityReaderMethodPath: $(SchemaName).Shared.$(CamelCasedResultName).ReadContract
  ReferencedEntityAssemblyPath: <Reference Include="BOA.Types.Kernel.Card.$(SchemaName)"><HintPath>D:\BOA\Server\bin\BOA.Types.Kernel.Card.$(SchemaName).dll</HintPath></Reference>
  ReferencedRepositoryAssemblyPath: <Reference Include="BOA.Business.Kernel.Card.$(SchemaName)"><HintPath>D:\BOA\Server\bin\BOA.Business.Kernel.Card.$(SchemaName).dll</HintPath></Reference>