ConnectionString: Server=srvxdev\zumrut;Database=BOACard;Trusted_Connection=True;
DatabaseEnumName: BOACard
CustomSQLNamesDefinedToProfileSql: SELECT objectid AS Id FROM dbo.objects WITH (NOLOCK) WHERE profileid = @profileId AND objecttype = 'CUSTOMSQL'
CustomSQL_Get_SQL_Item_Info: SELECT text AS Sql, schemaname AS SchemaName, CAST(resultcollectionflag AS INT) AS SqlResultIsCollection FROM dbo.objects WITH (NOLOCK) WHERE profileid = @profileId AND objecttype = 'CUSTOMSQL' AND objectid = @id
SQL_GetProfileIdList: SELECT profileid as ProfileId FROM dbo.profileskt WITH (NOLOCK)