using System.IO;
using System.Linq;

namespace BOAPlugins.ExportingModel
{
    public static class Handler
    {
        #region Public Methods
        public static ExportContract Handle(string solutionFilePath)
        {
            var directory = Path.GetDirectoryName(solutionFilePath);

            if (directory == null)
            {
                return new ExportContract
                {
                    ErrorMessage = "directory is null.@solutionFilePath:" + solutionFilePath
                };
            }

            const string configFileName = "AutoGeneratedModelsConfig.json";
            var configFilePath = Directory.GetFiles(directory, "*.json", SearchOption.AllDirectories).FirstOrDefault(f => f.EndsWith(configFileName));

            if (configFilePath == null)
            {
                return new ExportContract
                {
                    ErrorMessage = $"configFile not found.You must specify named json config file like:{configFileName}"
                };
            }

            var data = Exporter.Export(configFilePath);

            data.TargetFilePath = configFilePath.Replace(Path.GetFileName(configFilePath), "AutoGeneratedModels.tsx");

            var utilsDirectory = Path.GetDirectoryName(Path.GetDirectoryName(configFilePath)) + Path.DirectorySeparatorChar + "Utils" + Path.DirectorySeparatorChar;

            data.AutoGeneratedCodesInUtilDirectory_TargetFilePath = utilsDirectory + "AutoGenerated.tsx";

            return data;
        }
        #endregion
    }
}