contractInstanceName: '?'
contractInstancePropertyName: '?'
UPDATE_DATE: '$(contractInstanceName).$(contractInstancePropertyName) = DateTime.Now;'
UPDATE_USER_ID: '$(contractInstanceName).$(contractInstancePropertyName) = Context.ApplicationContext.Authentication.UserName;'
'string:UPDATE_TOKEN_ID': "$(contractInstanceName).$(contractInstancePropertyName) = Context.EngineContext.MainBusinessKey.ToString();"
'decimal:UPDATE_TOKEN_ID': "$(contractInstanceName).$(contractInstancePropertyName) = decimal.ToInt32(Context.EngineContext.MainBusinessKey);"
