using System.Collections.Generic;
using System.IO;
using BOAPlugins.ExportingModel;
using Handler = BOAPlugins.RemoveUnusedMessagesInTypescriptCodes.Handler;

namespace BOAPlugins.VSIntegration
{
    class Command
    {
        #region Public Properties
        public IVisualStudioLayer VisualStudio { get; set; }
        #endregion

        #region Public Methods
        public void RemoveUnusedMessagesInCsCodes()
        {
            var data = new ExportAsCSharpCodeData
            {
                solutionFilePath       = VisualStudio.GetSolutionFilePath(),
                RemoveUnusedProperties = true
            };

            MessagingExporter.ExportAsCSharpCode(data);
            if (data.ErrorMessage != null)
            {
                VisualStudio.UpdateStatusbarText(data.ErrorMessage);
                return;
            }

            Util.WriteFileIfContentNotEqual(data.TargetFilePath, data.GeneratedCode);
            VisualStudio.UpdateStatusbarText(Path.GetFileName(data.TargetFilePath) + " successfully updated.");
        }

        public void RemoveUnusedMessagesInTypescriptCodes()
        {
            var solutionFilePath = VisualStudio.GetSolutionFilePath();

            var directory = Path.GetDirectoryName(solutionFilePath);

            var propertyNames = new Dictionary<string, string>();

            Handler.Handle(directory, propertyNames);

            var data = new ExportAsCSharpCodeData
            {
                solutionFilePath  = solutionFilePath,
                usedPropertyNames = propertyNames
            };
            MessagingExporter.ExportAsTypeScriptCode(data);
            if (data.ErrorMessage != null)
            {
                VisualStudio.UpdateStatusbarText(data.ErrorMessage);
                return;
            }

            Util.WriteFileIfContentNotEqual(data.TargetFilePath, data.GeneratedCode);
            VisualStudio.UpdateStatusbarText("Messages.tsx successfully updated.");
        }

        public void UpdateMessageCs()
        {
            var data = new ExportAsCSharpCodeData
            {
                solutionFilePath = VisualStudio.GetSolutionFilePath()
            };

            MessagingExporter.ExportAsCSharpCode(data);
            if (data.ErrorMessage != null)
            {
                VisualStudio.UpdateStatusbarText(data.ErrorMessage);
                return;
            }

            Util.WriteFileIfContentNotEqual(data.TargetFilePath, data.GeneratedCode);
            VisualStudio.UpdateStatusbarText(Path.GetFileName(data.TargetFilePath) + " successfully updated.");
        }

        public void UpdateMessageTsx()
        {
            var data = new ExportAsCSharpCodeData
            {
                solutionFilePath = VisualStudio.GetSolutionFilePath()
            };

            MessagingExporter.ExportAsTypeScriptCode(data);
            if (data.ErrorMessage != null)
            {
                VisualStudio.UpdateStatusbarText(data.ErrorMessage);
                return;
            }

            Util.WriteFileIfContentNotEqual(data.TargetFilePath, data.GeneratedCode);
            VisualStudio.UpdateStatusbarText("Messages.tsx successfully updated.");
        }

        public void UpdateTypeScriptModels()
        {
            var solutionFilePath = VisualStudio.GetSolutionFilePath();

            var data = ExportingModel.Handler.Handle(solutionFilePath);

            if (data.ErrorMessage != null)
            {
                VisualStudio.UpdateStatusbarText(data.ErrorMessage);
                return;
            }

            Util.WriteFileIfContentNotEqual(data.TargetFilePath, data.GeneratedTSCode);

            Util.WriteFileIfContentNotEqual(data.AutoGeneratedCodesInUtilDirectory_TargetFilePath, data.AutoGeneratedCodesInUtilDirectory);

            VisualStudio.UpdateStatusbarText("TypeScript autogenerated codes successfully updated.");
        }
        #endregion
    }
}