using System.Collections.Generic;
using System.IO;
using BOAPlugins.ExportingModel;

namespace BOAPlugins.VSIntegration
{
    class Command
    {
        #region Public Properties
        public IVisualStudioLayer VisualStudio { get; set; }
        #endregion

        #region Public Methods
        public void UpdateMessageCs()
        {
            var data = new ExportAsCSharpCodeData
            {
                solutionFilePath = VisualStudio.GetSolutionFilePath()
            };

            var result = MessagingExporter.ExportAsCSharpCode(data);
            if (result.ErrorMessage != null)
            {
                VisualStudio.UpdateStatusbarText(result.ErrorMessage);
                return;
            }

            Util.WriteFileIfContentNotEqual(result.TargetFilePath, result.GeneratedCode);
            VisualStudio.UpdateStatusbarText(Path.GetFileName(result.TargetFilePath)+ " successfully updated.");
        }

        public void RemoveUnusedMessagesInCsCodes()
        {
            var data = new ExportAsCSharpCodeData
            {
                solutionFilePath = VisualStudio.GetSolutionFilePath(),
                RemoveUnusedProperties = true
            };

            var result = MessagingExporter.ExportAsCSharpCode(data);
            if (result.ErrorMessage != null)
            {
                VisualStudio.UpdateStatusbarText(result.ErrorMessage);
                return;
            }

            Util.WriteFileIfContentNotEqual(result.TargetFilePath, result.GeneratedCode);
            VisualStudio.UpdateStatusbarText(Path.GetFileName(result.TargetFilePath) + " successfully updated.");
        }


        public void UpdateMessageTsx()
        {
            var solutionFilePath = VisualStudio.GetSolutionFilePath();

            var result = MessagingExporter.ExportAsTypeScriptCode(solutionFilePath);
            if (result.ErrorMessage != null)
            {
                VisualStudio.UpdateStatusbarText(result.ErrorMessage);
                return;
            }

            Util.WriteFileIfContentNotEqual(result.TargetFilePath, result.GeneratedCode);
            VisualStudio.UpdateStatusbarText("Messages.tsx successfully updated.");
        }
        public void RemoveUnusedMessagesInTypescriptCodes()
        {
            var solutionFilePath = VisualStudio.GetSolutionFilePath();

            var directory = Path.GetDirectoryName(solutionFilePath);

            var propertyNames = new Dictionary<string, string>();

            BOAPlugins.RemoveUnusedMessagesInTypescriptCodes.Handler.Handle(directory,propertyNames);


            var result = MessagingExporter.ExportAsTypeScriptCode(solutionFilePath, propertyNames);
            if (result.ErrorMessage != null)
            {
                VisualStudio.UpdateStatusbarText(result.ErrorMessage);
                return;
            }

            Util.WriteFileIfContentNotEqual(result.TargetFilePath, result.GeneratedCode);
            VisualStudio.UpdateStatusbarText("Messages.tsx successfully updated.");
        }
        

        public void UpdateTypeScriptModels()
        {
            var solutionFilePath = VisualStudio.GetSolutionFilePath();

            var data = Handler.Handle(solutionFilePath);

            if (data.ErrorMessage != null)
            {
                VisualStudio.UpdateStatusbarText(data.ErrorMessage);
                return;
            }

            Util.WriteFileIfContentNotEqual(data.TargetFilePath, data.GeneratedTSCode);

            Util.WriteFileIfContentNotEqual(data.AutoGeneratedCodesInUtilDirectory_TargetFilePath, data.AutoGeneratedCodesInUtilDirectory);

            VisualStudio.UpdateStatusbarText("TypeScript autogenerated codes successfully updated.");
        }
        #endregion
    }
}