using System;
using System.Collections.Generic;

namespace BOAPlugins.Utility.TypescriptModelGeneration
{
    [Serializable]
    public class ExportInfo
    {
        #region Public Properties
        public string              Assembly         { get; set; }
        public ICollection<string> ExportClassNames { get; set; }
        #endregion
    }

    [Serializable]
    public class ExportData
    {
        #region Public Properties
        public string                  AutoGeneratedCodesInUtilDirectory { get; set; }
        public string                  ErrorMessage                      { get; set; }
        public ICollection<ExportInfo> ExportInfoList                    { get; set; }

        public string GeneratedTSCode { get; set; }
        public string InfoMessage     { get; set; }
        #endregion
    }
}