using BOA.CodeGeneration.Util;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace BOA.TfsAccess.Test
{
    [TestClass]
    public class TFSAccessForBOATest
    {
        #region Public Methods
        [TestMethod]
        public void DownloadFolder()
        {
            TFSAccessForBOA.DownloadFolder("D:\\work\\BOA.CardModules\\Dev\\AutoGeneratedCodes",
                                           "$/BOA.CardModules/Dev/AutoGeneratedCodes");
            
        }
        #endregion
    }
}