ConnectionString: Server=srvxdev\zumrut;Database=BOACard;Trusted_Connection=True;
TableCatalog: BOACard
DatabaseEnumName: BOACard
NotExportableTables:
- MRC.SENDING_REPORT_PARAMS_
- POS.POS_INVENTORY_
- STM.BUCKET_CLOSE_DETAIL
SqlSequenceInformationOfTable: "select  DISTINCT(columnname) AS TargetColumnName , (schemaname +'.' + sequencename) AS Name from BOACard.dbo.tablesequences WHERE schemaname = @schema AND tablename = @tableName"