using System;
using System.IO;
using BOA.Common.Helpers;
using BOA.Tasks;
using Data = CustomSqlInjectionToProject.BuildAutoGeneratedEntityCodesInDeveloperMachineData;

namespace CustomSqlInjectionToProject
{
    [Serializable]
    public class BuildAutoGeneratedEntityCodesInDeveloperMachineData
    {
    }

    public static class BuildAutoGeneratedEntityCodesInDeveloperMachine
    {
        #region Public Methods
        public static void Run(Data data)
        {
            PipeLine.Run(data,
                         //GetLatestVersionToLocal,
                         BuildTypes,
                         BuildBusiness);
        }
        #endregion

        #region Methods
        static void BuildBusiness(Data data)
        {

            const string search = @"D:\work\BOA.CardModules\Dev\AutoGeneratedCodes\";

            foreach (var file in Directory.GetFiles(search, "*.csproj"))
            {
                if (file.Contains("BOA.Business."))
                {
                    MSBuild.Build(new MSBuildData {ProjectFilePath = file});
                }
            }


           
        }

        static void BuildTypes(Data data)
        {
            const string search = @"D:\work\BOA.CardModules\Dev\AutoGeneratedCodes\";

            foreach (var file in Directory.GetFiles(search, "*.csproj"))
            {
                if (file.Contains("BOA.Types."))
                {
                    MSBuild.Build(new MSBuildData {ProjectFilePath = file});
                }
            }
        }

        //static void GetLatestVersionToLocal(Data data)
        //{
        //    const string tfsDirectory = @"D:\work\BOA.CardModules\Dev\AutoGeneratedCodes\CustomSqlInjectionToProject\Injector";

        //    // TFSAccessForBOA.DownloadFolder(tfsDirectory,tfsDirectory);
        //}
        #endregion
    }
}