cd\
cd windows
cd system32


robocopy "D:\github\WhiteStone\CustomSqlInjectionToProject\bin\Debug" "D:\work\BOA.CardModules\Dev\AutoGeneratedCodes\CustomSqlInjectionToProject\Injector" /E


if errorlevel 0 goto end1

:end1 echo FILECOPY for $(ProjectName) COMPLETED OK 
exit 0

