using System;
using BOA.Common.Helpers;

namespace CustomSqlInjectionToProject
{
    public class Program
    {
        #region Methods
        [STAThread]
        static void Main(string[] args)
        {
            Log.Push("args.length: " + args?.Length);
            Log.Push(args);

            // Injection.Inject(new []{"CC_OPERATIONS"});

            // BuildAutoGeneratedEntityCodesInDeveloperMachine.Run(new BuildAutoGeneratedEntityCodesInDeveloperMachineData());
            Injection.Inject(args);
            // Publisher.Publish(new PublisherData());
        }
        #endregion
    }
}