using System;
using System.Collections.Generic;
using BOA.Common.Helpers;

namespace CustomSqlInjectionToProject
{
    
    public class Program
    {
        #region Methods
        [STAThread]
        static void Main(string[] args)
        {

            // Injection.Inject(new []{"CC_OPERATIONS"});

            // BuildAutoGeneratedEntityCodesInDeveloperMachine.Run(new BuildAutoGeneratedEntityCodesInDeveloperMachineData());
             Injection.Inject(args);
            // Publisher.Publish(new PublisherData());

            
        }
        #endregion
    }
}