using System;
using BOA.CodeGeneration.Util;
using BOA.Common.Helpers;

namespace CustomSqlInjectionToProject
{
    [Serializable]
    public class PublisherData
    {
        #region Public Properties
        public string TfsComment { get; set; } = "2235# - Auto checkin for project injector.";
        #endregion
    }

    public static class Publisher
    {
        #region Public Methods
        public static void Publish(PublisherData data)
        {
            PipeLine.Run(data,
                         CopyDirectoryToAutoGeneratedDirectory,
                         CopyDirectoryToUnitSharedDirectory);
        }
        #endregion

        #region Methods
        static void CopyDirectoryToAutoGeneratedDirectory(PublisherData data)
        {
            const string source      = @"D:\github\WhiteStone\CustomSqlInjectionToProject\bin\Debug";
            const string destination = @"D:\work\BOA.CardModules\Dev\AutoGeneratedCodes\CustomSqlInjectionToProject\Injector";

            TFSAccessForBOA.CheckoutFile(destination);

            FileHelper.CopyDirectory(source, destination, true);

            TFSAccessForBOA.CheckInFile(destination, data.TfsComment);
        }

        static void CopyDirectoryToUnitSharedDirectory(PublisherData data)
        {
            const string source = @"D:\github\WhiteStone\CustomSqlInjectionToProject\bin\Debug";

            const string destination = @"\\srvktfs\KTBirimlerArasi\BT-Uygulama Gelistirme 3\Abdullah_Beyaztas\CustomSqlInjectionToProject\Injector";

            FileHelper.CopyDirectory(source, destination, true);
        }
        #endregion
    }
}