DefaultAssemblyReferences:
  - <Reference Include="$(EntityNamespace)"><HintPath>D:\BOA\Server\bin\$(EntityNamespace).dll</HintPath></Reference>
  - <Reference Include="System" />
  - <Reference Include="System.Core" />
  - <Reference Include="System.Data" />