namespace BOA.EntityGeneration.BOACardDatabaseSchemaToDllExporting
{
    public class ProjectExportLocation
    {
        const string Dir = @"D:\work\BOA.CardModules\Dev\AutoGeneratedCodes\";
        #region Public Methods
        public string GetExportLocationOfBusinessProject(string schemaName)
        {
            return $@"{Dir}{schemaName}\";
        }

        public string GetExportLocationOfTypeProject(string schemaName)
        {
            return $@"{Dir}{schemaName}\";
        }
        #endregion
    }
}