using System;
using System.IO;
using System.Linq;

namespace BOAPlugins.TypescriptModelGeneration
{
    [Serializable]
    public class GenerateFilePathInfo
    {
        #region Public Properties
        public string       AutoGenerated_tsx_FilePath             { get; private set; }
        public string       AutoGeneratedModels_tsx_FilePath       { get; private set; }
        public string       AutoGeneratedModelsConfig_JsonFilePath { get; private set; }
        public string       FilePathOf_FormAssistant_cs_In_Types   { get; private set; }
        public string       FormAssistant_tsx_FilePath             { get; private set; }
        public SolutionInfo SolutionInfo                           { get; set; }
        #endregion

        #region Public Methods
        public static GenerateFilePathInfo CreateFrom(string slnFilePath)
        {
            var solutionInfo = SolutionInfo.CreateFrom(slnFilePath);

            var data = new GenerateFilePathInfo
            {
                SolutionInfo = solutionInfo
            };

            if (solutionInfo.OneProjectFolder != null)
            {
                const string configFileName = "AutoGeneratedModelsConfig.json";

                var configFilePath = Directory.GetFiles(solutionInfo.OneProjectFolder, "*.json", SearchOption.AllDirectories).FirstOrDefault(f => f.EndsWith(configFileName));
                if (configFilePath != null)
                {
                    data.AutoGeneratedModelsConfig_JsonFilePath = configFilePath;

                    data.AutoGeneratedModels_tsx_FilePath = configFilePath.Replace(Path.GetFileName(configFilePath), "AutoGeneratedModels.tsx");

                    var utilsDirectory = Path.GetDirectoryName(Path.GetDirectoryName(configFilePath)) + Path.DirectorySeparatorChar + "Utils" + Path.DirectorySeparatorChar;

                    data.AutoGenerated_tsx_FilePath = utilsDirectory + "AutoGenerated.tsx";
                }
            }

            if (solutionInfo.OneProjectFolder != null)
            {
                data.FormAssistant_tsx_FilePath = solutionInfo.OneProjectFolder + @"ClientApp\utils\FormAssistant.tsx";
            }

            data.FilePathOf_FormAssistant_cs_In_Types = solutionInfo.TypesProjectFolder + "FormAssistant.cs";

            return data;
        }
        #endregion
    }
}