using System;
using System.IO;
using System.Linq;

namespace BOAPlugins.TypescriptModelGeneration
{
    [Serializable]
    public class SolutionInfo
    {
        #region Public Properties
        public string AutoGenerated_tsx_FilePath             { get; private set; }
        public string AutoGeneratedModels_tsx_FilePath       { get; private set; }
        public string AutoGeneratedModelsConfig_JsonFilePath { get; private set; }
        public bool   IsValid                                { get; private set; }
        public string SlnFilePath                            { get; private set; }
        #endregion

        #region Public Methods
        public static SolutionInfo CreateFrom(string slnFilePath)
        {
            var data = new SolutionInfo();

            var directory = Path.GetDirectoryName(slnFilePath);

            if (directory == null)
            {
                return data;
            }

            const string configFileName = "AutoGeneratedModelsConfig.json";

            var configFilePath = Directory.GetFiles(directory, "*.json", SearchOption.AllDirectories).FirstOrDefault(f => f.EndsWith(configFileName));
            if (configFilePath == null)
            {
                return data;
            }

            data.AutoGeneratedModelsConfig_JsonFilePath = configFilePath;

            data.AutoGeneratedModels_tsx_FilePath = configFilePath?.Replace(Path.GetFileName(configFilePath), "AutoGeneratedModels.tsx");

            var utilsDirectory = Path.GetDirectoryName(Path.GetDirectoryName(configFilePath)) + Path.DirectorySeparatorChar + "Utils" + Path.DirectorySeparatorChar;

            data.AutoGenerated_tsx_FilePath = utilsDirectory + "AutoGenerated.tsx";

            data.IsValid = true;

            return data;
        }
        #endregion
    }
}