using System;
using System.Collections.Generic;
using Mono.Cecil;

namespace BOAPlugins.TypescriptModelGeneration
{
    /// <summary>
    ///     The export information
    /// </summary>
    [Serializable]
    public class ExportInfo
    {
        #region Public Properties
        /// <summary>
        ///     Gets or sets the assembly.
        /// </summary>
        public string Assembly { get; set; }

        /// <summary>
        ///     Gets or sets the export class names.
        /// </summary>
        public ICollection<string> ExportClassNames { get; set; }
        #endregion
    }

    /// <summary>
    ///     The export data
    /// </summary>
    [Serializable]
    public class ExportData
    {
        #region Public Properties
        /// <summary>
        ///     Gets or sets the automatic generated codes in utility directory.
        /// </summary>
        public string AutoGeneratedCodesInUtilDirectory { get; set; }

        /// <summary>
        ///     Gets or sets the error message.
        /// </summary>
        public string ErrorMessage { get; set; }

        /// <summary>
        ///     Gets or sets the export information list.
        /// </summary>
        public ICollection<ExportInfo> ExportInfoList { get; set; }

        /// <summary>
        ///     Gets or sets the generated ts code.
        /// </summary>
        public string GeneratedTSCode { get; set; }

        /// <summary>
        ///     Gets or sets the information message.
        /// </summary>
        public string InfoMessage { get; set; }
        #endregion

        #region Properties
        /// <summary>
        ///     Gets or sets the request type full names.
        /// </summary>
        internal IReadOnlyList<string> RequestTypeFullNames { get; set; }
        internal IReadOnlyList<TypeDefinition> TypeDefinitions { get; set; }
        #endregion
    }
}