using System.IO;
using BOA.CodeGeneration.Util;
using BOA.Common.Helpers;

namespace BOA.OneDesigner.Publishing
{
    public class Publisher
    {
        #region Public Methods
        public static void Publish()
        {

            BOA.TfsAccess.Publisher.Zip();

            new ZipAssemblyResolver("D:\\github\\WhiteStone\\bin\\WhiteStone.zip").AttachToCurrentDomain();

            new ZipAssemblyResolver("D:\\github\\WhiteStone\\bin\\BOA.TfsAccess.zip").AttachToCurrentDomain();

            const string prefix = @"D:\github\WhiteStone\BOA.OneDesigner\bin\Debug\";

            var files = new string[]
            {
                prefix + "MainForm\\View.json",
                prefix + "WhiteStone.dll",
                prefix + "BOA.OneDesigner.dll",
                prefix + "BOAPlugins.dll",
                prefix + "BOA.CodeGeneration.dll",
                prefix + "BOA.EntityGeneration.dll",
                prefix + "BOA.TfsAccess.dll",
                prefix + "WhiteStone.UI.Container.exe",
                prefix + "WhiteStone.UI.Container.exe.config",
                prefix + "CustomUIMarkupLanguage.dll",
                prefix + "Intellibox.dll",
                prefix + "MahApps.Metro.dll",
                prefix + "ControlzEx.dll",
                prefix + "Microsoft.Xaml.Behaviors.dll",
                prefix + "Newtonsoft.Json.dll",
                prefix + "Ninject.dll",
                prefix + "Notifications.Wpf.dll",
                prefix + "Mono.Cecil.dll",
                prefix + "Mono.Cecil.Mdb.dll",
                prefix + "Mono.Cecil.Pdb.dll",
                prefix + "Mono.Cecil.Rocks.dll",
                prefix + "Microsoft.TeamFoundation.Core.WebApi.dll",
                prefix + "Microsoft.TeamFoundation.Work.WebApi.dll",
                prefix + "Microsoft.TeamFoundation.WorkItemTracking.WebApi.dll",
                prefix + "Microsoft.TeamFoundation.Diff.dll",
                prefix + "Microsoft.TeamFoundation.VersionControl.Client.dll",
                prefix + "Microsoft.TeamFoundation.VersionControl.Common.dll",
                prefix + "Microsoft.TeamFoundation.VersionControl.Common.Integration.dll",
                prefix + "Microsoft.TeamFoundation.WorkItemTracking.Client.DataStoreLoader.dll",
                prefix + "Microsoft.TeamFoundation.WorkItemTracking.Client.dll",
                prefix + "Microsoft.TeamFoundation.WorkItemTracking.Client.QueryLanguage.dll",
                prefix + "Microsoft.TeamFoundation.WorkItemTracking.Common.dll",
                prefix + "Microsoft.TeamFoundation.WorkItemTracking.Proxy.dll",
                prefix + "Microsoft.TeamFoundation.Client.dll",
                prefix + "Microsoft.TeamFoundation.Common.dll",
                prefix + "Microsoft.VisualStudio.Services.WebApi.dll",
                prefix + "Microsoft.VisualStudio.Services.Common.dll",
                prefix + "Microsoft.VisualStudio.Services.Client.dll",
                prefix + "Microsoft.ServiceBus.dll",
                prefix + "System.Net.Http.Formatting.dll",
                prefix + "Microsoft.SqlServer.TransactSql.ScriptDom.dll",
                prefix + "System.IdentityModel.Tokens.Jwt.dll"
            };

            const string newlyCreatedZipFilePath = "D:\\github\\WhiteStone\\bin\\BOA.OneDesigner.zip";

            ZipHelper.CompressFiles(newlyCreatedZipFilePath, files);


            const string destinationPath = "D:\\work\\BOA.CardModules\\Dev\\AutoGeneratedCodes\\BOA.OneDesigner\\BOA.OneDesigner.zip";

            TFSAccessForBOA.CheckoutFile(destinationPath);

            File.Copy(newlyCreatedZipFilePath, destinationPath, true);

            const string comment = "2235# - Auto checkin.";

            TFSAccessForBOA.CheckInFile(destinationPath, comment);

      

            TFSAccessForBOA.CheckoutFile("D:\\work\\BOA.CardModules\\Dev\\AutoGeneratedCodes\\BOA.OneDesigner\\BOA.OneDesigner.exe");
            File.Copy( @"D:\github\WhiteStone\BOA.OneDesigner.Starter\bin\Debug\BOA.OneDesigner.exe",
                       "D:\\work\\BOA.CardModules\\Dev\\AutoGeneratedCodes\\BOA.OneDesigner\\BOA.OneDesigner.exe", true);

            TFSAccessForBOA.CheckInFile(destinationPath, comment);
        }
        #endregion
    }
}