using System;
using BOA.CodeGeneration.Util;
using BOA.Common.Helpers;

namespace BOA.OneDesigner.Publishing
{
    [Serializable]
    public class PublisherData
    {
        #region Public Properties
        public string TfsComment { get; set; } = "2235# - Auto checkin for project injector.";
        #endregion
    }

    class Publisher
    {
        #region Public Methods
        public static void Publish(PublisherData data)
        {
            const string destination = @"D:\work\BOA.CardModules\Dev\AutoGeneratedCodes\BOA.OneDesigner\BOA.OneDesigner.zip";

            TFSAccessForBOA.CheckoutFile(destination);

            FileHelper.CopyDirectory(@"D:\github\WhiteStone\bin\BOA.OneDesigner.zip", destination, true);

            TFSAccessForBOA.CheckInFile(destination, data.TfsComment);
        }
        #endregion
    }
}