namespace BOA.EntityGeneration
{
    public enum SqlReaderMethods
    {
        GetStringValue,
        GetDecimalValue,
        GetDecimalNullableValue,
        GetBooleanValue,
        GetBooleanNullableValue,
        GetBooleanNullableValue2,
        GetDateTimeValue,
        GetDateTimeNullableValue,
        GetInt64Value,
        GetInt64NullableValue,
        GetGUIDValue,
        GetTimeSpanValue,
        GetInt32NullableValue,
        GetInt32Value,
        GetInt16NullableValue,
        GetInt16Value,
        GetByteNullableValue,
        GetByteValue,
        GetDoubleNullableValue,
        GetDoubleValue,
        GetSingleNullableValue,
        GetSingleValue,
        GetBinaryValue,
        GetTimeStampValue,
        GetSecureStringValue
    }
}