using BOA.CodeGeneration.Util;
using BOA.Common.Helpers;

namespace BOACardEntityGenerationWrapper
{
    public static class Publisher
    {
        #region Constants
        const string Source = @"D:\github\WhiteStone\BOACardEntityGenerationWrapper\bin\Debug";
        #endregion

        #region Public Methods
        public static void Publish(PublisherData data)
        {
            PipeLine.Run(data,
                         CopyDirectoryToAutoGeneratedDirectory,
                         CopyDirectoryToUnitSharedDirectory);
        }
        #endregion

        #region Methods
        static void CopyDirectoryToAutoGeneratedDirectory(PublisherData data)
        {
            const string destination = @"D:\work\BOA.CardModules\Dev\AutoGeneratedCodes\BOACard.EntityGeneration\Generator";

            TFSAccessForBOA.CheckoutFile(destination);

            FileHelper.CopyDirectory(Source, destination, true);

            TFSAccessForBOA.CheckInFile(destination, data.TfsComment);
        }

        static void CopyDirectoryToUnitSharedDirectory(PublisherData data)
        {
            const string destinationDirectory = @"\\srvktfs\KTBirimlerArasi\BT-Uygulama Gelistirme 3\Abdullah_Beyaztas\BOACardEntityGeneration\Generator";
            FileHelper.CopyDirectory(Source, destinationDirectory, true);
        }
        #endregion
    }
}