using System;
using BOA.CodeGeneration.Util;
using BOA.Common.Helpers;

namespace BOACardEntityGenerationWrapper
{
    [Serializable]
    public class PublisherData
    {
        #region Public Properties
        public string TfsComment { get; set; } = "2235# - Auto checkin for project injector.";
        #endregion
    }
    
    public static class Publisher
    {
        const string source = @"D:\github\WhiteStone\BOACardEntityGenerationWrapper\bin\Debug";

        #region Public Methods
        public static void Publish(PublisherData data)
        {
            PipeLine.Run(data,
                         CopyDirectoryToAutoGeneratedDirectory,
                         CopyDirectoryToUnitSharedDirectory);
        }
        #endregion

        #region Methods
        static void CopyDirectoryToAutoGeneratedDirectory(PublisherData data)
        {
            const string destination = @"D:\work\BOA.CardModules\Dev\AutoGeneratedCodes\BOACard.EntityGeneration\Generator";

            TFSAccessForBOA.CheckoutFile(destination);

            FileHelper.CopyDirectory(source, destination, true);

            TFSAccessForBOA.CheckInFile(destination, data.TfsComment);
        }

        static void CopyDirectoryToUnitSharedDirectory(PublisherData data)
        {
            


            FileHelper.CopyDirectory(source, @"\\srvktfs\KTBirimlerArasi\BT-Uygulama Gelistirme 3\Abdullah_Beyaztas\BOACardEntityGeneration\Generator", true);
            FileHelper.CopyDirectory(source,@"\\srvktfs\KTBirimlerArasi\BT-Uygulama Gelistirme 3\Abdullah_Beyaztas\BOACardEntityGeneration\Generator",true);
        }
        #endregion
    }
}